"""
Calibrated Uncertainty Head — Post-hoc binary classifier predicting
p(|risk_partial - risk_oracle| > tau) via BCE + temperature scaling.

Training data is generated by enumerating clinical-ordering prefix masks
on patients with complete modalities.
"""

import itertools
import os
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


class CalibratedUncertaintyHead(nn.Module):
    """MLP predicting uncertainty from (embedding, mask).

    Output: p(|risk_partial - risk_oracle| > tau) in [0, 1]
    Training: BCEWithLogitsLoss on raw logits
    Inference: sigmoid(logit / temperature)

    Args:
        embedding_dim: predictor's embedding dimension (default 128).
        n_modalities:  number of modalities (default 4).
        hidden_dim:    MLP hidden layer size.
        mode:          "binary" (default) or "regression".
    """

    def __init__(
        self,
        embedding_dim: int = 128,
        n_modalities: int = 4,
        hidden_dim: int = 64,
        mode: str = "binary",
    ):
        super().__init__()
        self.embedding_dim = embedding_dim
        self.n_modalities = n_modalities
        self.hidden_dim = hidden_dim
        self.mode = mode
        input_dim = embedding_dim + n_modalities

        if mode == "regression":
            # Regression: Softplus output
            self.net = nn.Sequential(
                nn.Linear(input_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, hidden_dim // 2),
                nn.ReLU(),
                nn.Linear(hidden_dim // 2, 1),
                nn.Softplus(),
            )
        else:
            # Binary: raw logits, activation applied in forward()
            self.net = nn.Sequential(
                nn.Linear(input_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, hidden_dim // 2),
                nn.ReLU(),
                nn.Linear(hidden_dim // 2, 1),
            )

        # Temperature for post-hoc calibration (binary mode only).
        # Default T=1.0 (no scaling). Optimized after training via
        # calibrate_temperature() on validation set.
        self.temperature = nn.Parameter(torch.ones(1), requires_grad=False)

        self._init_weights()

    def _init_weights(self):
        for m in self.net:
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, nonlinearity="relu")
                nn.init.zeros_(m.bias)

    def forward(
        self, embedding: torch.Tensor, mask: torch.Tensor
    ) -> torch.Tensor:
        """
        Args:
            embedding: (B, embedding_dim) from frozen predictor.
            mask:      (B, n_modalities) current acquired mask.

        Returns:
            (B,) uncertainty scores.
                Binary mode:     calibrated probability in [0, 1].
                Regression mode: non-negative discrepancy estimate.
        """
        x = torch.cat([embedding, mask], dim=-1)
        out = self.net(x).squeeze(-1)
        if self.mode == "binary":
            return torch.sigmoid(out / self.temperature)
        return out

    def get_logits(
        self, embedding: torch.Tensor, mask: torch.Tensor
    ) -> torch.Tensor:
        """Return raw logits before activation (binary mode).

        Used during training (BCEWithLogitsLoss) and temperature calibration.

        Args:
            embedding: (B, embedding_dim)
            mask:      (B, n_modalities)

        Returns:
            (B,) raw logits.
        """
        x = torch.cat([embedding, mask], dim=-1)
        return self.net(x).squeeze(-1)


# ═══════════════════════════════════════════════════════════════════════════
# Training data generation
# ═══════════════════════════════════════════════════════════════════════════
def generate_training_data(
    predictor: nn.Module,
    features: np.ndarray,
    masks: np.ndarray,
    device: str = "cuda",
    min_modalities: int = 2,
    clinical_ordering_only: bool = True,
    binary_threshold: Optional[float] = None,
    debug: bool = False,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate (embedding, mask_subset, target) training triples.

    For each patient with ≥ ``min_modalities`` available modalities:
      - Compute risk with all available modalities (oracle)
      - Enumerate mask subsets, compute partial embedding + risk
      - Regression target: |risk_partial − risk_oracle|
      - Binary target (if binary_threshold is set): 1[|error| > threshold]

    When ``clinical_ordering_only=True`` (default), only the 4 clinical-chain
    prefix masks are used: [1,0,0,0], [1,1,0,0], [1,1,1,0], [1,1,1,1].

    When ``clinical_ordering_only=False``, all non-empty subsets are enumerated
    (all non-empty subsets).

    Args:
        predictor:              frozen SurvivalPredictor on *device*.
        features:               (N, n_mod, feat_dim) patient features.
        masks:                  (N, n_mod) availability masks.
        device:                 torch device.
        min_modalities:         skip patients with fewer available modalities.
        clinical_ordering_only: if True, use only clinical-chain prefix masks.
        binary_threshold:       if not None, binarize targets: 1[|error| > τ].
        debug:                  verbose.

    Returns:
        embeddings:  (M, embedding_dim) numpy array.
        mask_subsets: (M, n_mod) numpy array.
        targets:      (M,) numpy array.
                      Regression: |risk_partial − risk_oracle|
                      Binary:     0.0 or 1.0
    """
    predictor.eval()
    n_patients, n_mod, feat_dim = features.shape

    # Clinical ordering: Demo(0) → Rad(1) → Path(2) → Gen(3)
    # Prefix masks the agent actually encounters:
    clinical_prefix_masks = [
        np.array([1, 0, 0, 0], dtype=np.float32),  # demo only
        np.array([1, 1, 0, 0], dtype=np.float32),  # demo + rad
        np.array([1, 1, 1, 0], dtype=np.float32),  # demo + rad + path
        # [1,1,1,1] is the oracle (target=0), added separately below
    ]

    all_embeddings = []
    all_masks = []
    all_targets = []

    with torch.no_grad():
        for i in range(n_patients):
            avail = masks[i]  # (n_mod,)
            available_indices = [j for j in range(n_mod) if avail[j] > 0.5]

            if len(available_indices) < min_modalities:
                continue

            # Oracle: predict with all available modalities
            feat_full = torch.from_numpy(features[i]).float().unsqueeze(0).to(device)
            mask_full = torch.from_numpy(avail).float().unsqueeze(0).to(device)
            oracle_risk = predictor.get_risk_score(feat_full, mask_full).cpu().item()

            if clinical_ordering_only:
                # Only use clinical-chain prefix masks
                for sub_mask in clinical_prefix_masks:
                    # Skip if patient doesn't have all modalities in this prefix
                    if any(sub_mask[j] > 0.5 and avail[j] < 0.5 for j in range(n_mod)):
                        continue

                    sub_feat = features[i].copy()
                    for j in range(n_mod):
                        if sub_mask[j] < 0.5:
                            sub_feat[j] = 0.0

                    feat_t = torch.from_numpy(sub_feat).float().unsqueeze(0).to(device)
                    mask_t = torch.from_numpy(sub_mask.copy()).float().unsqueeze(0).to(device)

                    partial_risk = predictor.get_risk_score(feat_t, mask_t).cpu().item()
                    partial_emb = predictor.get_embedding(feat_t, mask_t).cpu().numpy()[0]

                    raw_target = abs(partial_risk - oracle_risk)
                    target = float(raw_target > binary_threshold) if binary_threshold is not None else raw_target

                    all_embeddings.append(partial_emb)
                    all_masks.append(sub_mask.copy())
                    all_targets.append(target)
            else:
                # Enumerate all non-empty strict subsets
                for size in range(1, len(available_indices)):
                    for subset in itertools.combinations(available_indices, size):
                        sub_mask = np.zeros(n_mod, dtype=np.float32)
                        for idx in subset:
                            sub_mask[idx] = 1.0

                        sub_feat = features[i].copy()
                        for j in range(n_mod):
                            if sub_mask[j] < 0.5:
                                sub_feat[j] = 0.0

                        feat_t = torch.from_numpy(sub_feat).float().unsqueeze(0).to(device)
                        mask_t = torch.from_numpy(sub_mask).float().unsqueeze(0).to(device)

                        partial_risk = predictor.get_risk_score(feat_t, mask_t).cpu().item()
                        partial_emb = predictor.get_embedding(feat_t, mask_t).cpu().numpy()[0]

                        raw_target = abs(partial_risk - oracle_risk)
                        target = float(raw_target > binary_threshold) if binary_threshold is not None else raw_target

                        all_embeddings.append(partial_emb)
                        all_masks.append(sub_mask)
                        all_targets.append(target)

            # Also add the full-mask case with target = 0
            full_emb = predictor.get_embedding(feat_full, mask_full).cpu().numpy()[0]
            all_embeddings.append(full_emb)
            all_masks.append(avail.copy())
            all_targets.append(0.0)

    embeddings = np.array(all_embeddings, dtype=np.float32)
    mask_subsets = np.array(all_masks, dtype=np.float32)
    targets = np.array(all_targets, dtype=np.float32)

    if debug:
        n_patients_used = sum(
            1 for i in range(n_patients)
            if sum(1 for j in range(n_mod) if masks[i][j] > 0.5) >= min_modalities
        )
        mode = "clinical-ordering" if clinical_ordering_only else "all-subsets"
        if binary_threshold is not None:
            pos_rate = targets.mean() if len(targets) > 0 else 0
            print(
                f"[CALIB] Generated {len(targets)} samples ({mode}, "
                f"binary τ={binary_threshold}) from {n_patients_used} patients "
                f"(positive rate: {pos_rate:.3f})"
            )
        else:
            print(
                f"[CALIB] Generated {len(targets)} training samples ({mode}) "
                f"from {n_patients_used} patients "
                f"(target range: [{targets.min():.4f}, {targets.max():.4f}], "
                f"mean: {targets.mean():.4f})"
            )

    return embeddings, mask_subsets, targets


# ═══════════════════════════════════════════════════════════════════════════
# Temperature calibration (Guo et al., ICML 2017)
# ═══════════════════════════════════════════════════════════════════════════
def calibrate_temperature(
    head: 'CalibratedUncertaintyHead',
    val_embeddings: np.ndarray,
    val_masks: np.ndarray,
    val_targets: np.ndarray,
    device: str = "cuda",
    max_iter: int = 50,
    lr: float = 0.01,
    debug: bool = False,
) -> float:
    """Post-hoc temperature scaling on validation set.

    Optimizes a single scalar T to minimize NLL (BCE) on validation logits:
        p = sigmoid(logit / T)
        loss = BCE(p, y)

    The head's temperature parameter is updated in-place.

    Args:
        head:            trained CalibratedUncertaintyHead (binary mode).
        val_embeddings:  (M, embedding_dim) validation embeddings.
        val_masks:       (M, n_mod) validation mask subsets.
        val_targets:     (M,) binary targets (0 or 1).
        device:          torch device.
        max_iter:        LBFGS max iterations.
        lr:              LBFGS learning rate.
        debug:           verbose.

    Returns:
        Optimal temperature T.
    """
    head.eval()

    emb_t = torch.from_numpy(val_embeddings).float().to(device)
    mask_t = torch.from_numpy(val_masks).float().to(device)
    target_t = torch.from_numpy(val_targets).float().to(device)

    # Get logits (frozen)
    with torch.no_grad():
        logits = head.get_logits(emb_t, mask_t)

    # Optimize temperature
    temperature = nn.Parameter(torch.ones(1, device=device))
    optimizer = optim.LBFGS([temperature], lr=lr, max_iter=max_iter)

    def closure():
        optimizer.zero_grad()
        loss = F.binary_cross_entropy_with_logits(
            logits / temperature, target_t
        )
        loss.backward()
        return loss

    optimizer.step(closure)

    optimal_T = temperature.item()

    # Clamp to reasonable range
    optimal_T = max(0.1, min(optimal_T, 10.0))

    # Update head's temperature in-place
    head.temperature.data.fill_(optimal_T)

    if debug:
        # Compute ECE before and after
        with torch.no_grad():
            probs_before = torch.sigmoid(logits)
            probs_after = torch.sigmoid(logits / optimal_T)
            ece_before = _compute_ece(probs_before.cpu().numpy(), val_targets)
            ece_after = _compute_ece(probs_after.cpu().numpy(), val_targets)
        print(
            f"[CALIB] Temperature scaling: T={optimal_T:.4f}, "
            f"ECE {ece_before:.4f} → {ece_after:.4f}"
        )

    print(f"[CALIB] Temperature calibrated: T={optimal_T:.4f}")
    return optimal_T


def _compute_ece(
    probs: np.ndarray, targets: np.ndarray, n_bins: int = 15
) -> float:
    """Expected Calibration Error (ECE).

    ECE = Σ (|B_m| / N) × |acc(B_m) − conf(B_m)|

    Args:
        probs:   (N,) predicted probabilities.
        targets: (N,) binary labels (0 or 1).
        n_bins:  number of equal-width bins.

    Returns:
        ECE value in [0, 1].
    """
    bin_boundaries = np.linspace(0, 1, n_bins + 1)
    ece = 0.0
    n = len(probs)

    for i in range(n_bins):
        lo, hi = bin_boundaries[i], bin_boundaries[i + 1]
        in_bin = (probs > lo) & (probs <= hi) if i > 0 else (probs >= lo) & (probs <= hi)
        n_in_bin = in_bin.sum()
        if n_in_bin == 0:
            continue
        avg_conf = probs[in_bin].mean()
        avg_acc = targets[in_bin].mean()
        ece += (n_in_bin / n) * abs(avg_acc - avg_conf)

    return float(ece)


# ═══════════════════════════════════════════════════════════════════════════
# Training loop
# ═══════════════════════════════════════════════════════════════════════════
def train_calibrated_head(
    predictor: nn.Module,
    train_features: np.ndarray,
    train_masks: np.ndarray,
    val_features: Optional[np.ndarray] = None,
    val_masks: Optional[np.ndarray] = None,
    embedding_dim: int = 128,
    n_modalities: int = 4,
    hidden_dim: int = 64,
    mode: str = "binary",
    binary_threshold: float = 0.3,
    lr: float = 0.001,
    weight_decay: float = 1e-4,
    n_epochs: int = 100,
    batch_size: int = 128,
    patience: int = 15,
    min_modalities: int = 2,
    clinical_ordering_only: bool = True,
    device: str = "cuda",
    debug: bool = False,
) -> CalibratedUncertaintyHead:
    """Train a calibrated uncertainty head from scratch.

    Args:
        predictor:              frozen SurvivalPredictor.
        train_features:         (N_train, n_mod, feat_dim).
        train_masks:            (N_train, n_mod).
        val_features:           (N_val, n_mod, feat_dim) or None.
        val_masks:              (N_val, n_mod) or None.
        embedding_dim:          predictor embedding dimension.
        n_modalities:           number of modalities.
        hidden_dim:             MLP hidden size.
        mode:                   "binary" (default) or "regression".
        binary_threshold:       τ for binary mode (default 0.3).
        lr:                     learning rate.
        weight_decay:           L2 regularisation.
        n_epochs:               maximum training epochs.
        batch_size:             mini-batch size.
        patience:               early stopping patience.
        min_modalities:         minimum modalities for a patient to be used.
        clinical_ordering_only: if True, use only clinical-chain prefix masks.
        device:                 torch device.
        debug:                  verbose.

    Returns:
        trained CalibratedUncertaintyHead on *device*, in eval mode.
        If binary mode, temperature is calibrated on val set.
    """
    is_binary = (mode == "binary")
    thresh = binary_threshold if is_binary else None

    print(f"[CALIB] Mode: {mode}" + (f", threshold τ={binary_threshold}" if is_binary else ""))
    print("[CALIB] Generating training data...")
    train_emb, train_sub_masks, train_targets = generate_training_data(
        predictor, train_features, train_masks,
        device=device, min_modalities=min_modalities,
        clinical_ordering_only=clinical_ordering_only,
        binary_threshold=thresh, debug=debug,
    )

    val_emb, val_sub_masks, val_targets = None, None, None
    val_loader = None
    if val_features is not None and val_masks is not None:
        print("[CALIB] Generating validation data...")
        val_emb, val_sub_masks, val_targets = generate_training_data(
            predictor, val_features, val_masks,
            device=device, min_modalities=min_modalities,
            clinical_ordering_only=clinical_ordering_only,
            binary_threshold=thresh, debug=debug,
        )
        if len(val_targets) > 0:
            val_ds = TensorDataset(
                torch.from_numpy(val_emb),
                torch.from_numpy(val_sub_masks),
                torch.from_numpy(val_targets),
            )
            val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)

    # Build data loader
    train_ds = TensorDataset(
        torch.from_numpy(train_emb),
        torch.from_numpy(train_sub_masks),
        torch.from_numpy(train_targets),
    )
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)

    # Model
    head = CalibratedUncertaintyHead(
        embedding_dim=embedding_dim,
        n_modalities=n_modalities,
        hidden_dim=hidden_dim,
        mode=mode,
    ).to(device)

    optimizer = optim.Adam(head.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=5, min_lr=1e-6
    )

    if is_binary:
        # BCE on logits for numerical stability
        criterion = nn.BCEWithLogitsLoss()
    else:
        criterion = nn.MSELoss()

    best_val_loss = float("inf")
    best_state = None
    epochs_no_improve = 0

    print(f"[CALIB] Training: {len(train_ds)} samples, batch_size={batch_size}")
    for epoch in range(n_epochs):
        # Train
        head.train()
        train_loss_sum = 0.0
        n_batches = 0
        for emb_b, mask_b, target_b in train_loader:
            emb_b = emb_b.to(device)
            mask_b = mask_b.to(device)
            target_b = target_b.to(device)

            if is_binary:
                pred = head.get_logits(emb_b, mask_b)
            else:
                pred = head(emb_b, mask_b)
            loss = criterion(pred, target_b)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss_sum += loss.item()
            n_batches += 1

        train_loss = train_loss_sum / max(n_batches, 1)

        # Validate
        val_loss = train_loss  # fallback if no val set
        if val_loader is not None:
            head.eval()
            val_loss_sum = 0.0
            n_val = 0
            with torch.no_grad():
                for emb_b, mask_b, target_b in val_loader:
                    emb_b = emb_b.to(device)
                    mask_b = mask_b.to(device)
                    target_b = target_b.to(device)
                    if is_binary:
                        pred = head.get_logits(emb_b, mask_b)
                    else:
                        pred = head(emb_b, mask_b)
                    val_loss_sum += criterion(pred, target_b).item()
                    n_val += 1
            val_loss = val_loss_sum / max(n_val, 1)

        scheduler.step(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.clone() for k, v in head.state_dict().items()}
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        if debug and (epoch + 1) % 10 == 0:
            print(
                f"  [CALIB] Epoch {epoch+1:3d}: "
                f"train_loss={train_loss:.6f}, val_loss={val_loss:.6f}, "
                f"lr={optimizer.param_groups[0]['lr']:.2e}"
            )

        if epochs_no_improve >= patience:
            if debug:
                print(f"  [CALIB] Early stopping at epoch {epoch+1}")
            break

    # Load best
    if best_state is not None:
        head.load_state_dict(best_state)
    head.eval()

    print(f"[CALIB] Training complete. Best val loss: {best_val_loss:.6f}")

    # Post-hoc temperature scaling (binary mode only)
    if is_binary and val_emb is not None and len(val_targets) > 0:
        print("[CALIB] Calibrating temperature on validation set...")
        calibrate_temperature(
            head, val_emb, val_sub_masks, val_targets,
            device=device, debug=debug,
        )

    return head


# ═══════════════════════════════════════════════════════════════════════════
# Save / Load
# ═══════════════════════════════════════════════════════════════════════════
def save_calibrated_head(
    head: CalibratedUncertaintyHead, path: str, metadata: Optional[dict] = None
):
    """Save the calibrated head checkpoint."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    data = {
        "model_state_dict": head.state_dict(),
        "embedding_dim": head.embedding_dim,
        "n_modalities": head.n_modalities,
        "hidden_dim": head.hidden_dim,
        "mode": head.mode,
    }
    if metadata:
        data["metadata"] = metadata
    torch.save(data, path)
    print(f"[CALIB] Saved calibrated head to {path}")


def load_calibrated_head(
    path: str, device: str = "cuda", hidden_dim: int = 64
) -> CalibratedUncertaintyHead:
    """Load a calibrated head from checkpoint.

    Handles checkpoints that may lack
    'mode' and 'hidden_dim' fields.
    """
    data = torch.load(path, map_location=device, weights_only=False)

    mode = data.get("mode", "binary")
    hdim = data.get("hidden_dim", hidden_dim)

    head = CalibratedUncertaintyHead(
        embedding_dim=data.get("embedding_dim", 128),
        n_modalities=data.get("n_modalities", 4),
        hidden_dim=hdim,
        mode=mode,
    )

    # Handle loading old checkpoints that don't have temperature parameter
    state_dict = data["model_state_dict"]
    if "temperature" not in state_dict:
        state_dict["temperature"] = torch.ones(1)

    head.load_state_dict(state_dict)
    head.to(device).eval()
    for p in head.parameters():
        p.requires_grad_(False)

    T_str = f", T={head.temperature.item():.4f}" if mode == "binary" else ""
    print(f"[CALIB] Loaded calibrated head from {path} (mode={mode}{T_str})")
    return head
